// Purpose: Public duel, bracket, estimation, append-only history, and local submission server API.
import{appendFile,mkdir,readFile}from'node:fs/promises';import{createServer}from'node:http';import{dirname,join}from'node:path';import{fileURLToPath}from'node:url';import{estimateCostUsd,estimateTokens}from'./jev-client.mjs';export{createFakeProvider,createJevClient}from'./jev-client.mjs';const ROOT=dirname(dirname(fileURLToPath(import.meta.url)));
export function validatePack(pack){if(!pack?.id||!pack?.title||!Array.isArray(pack.criteria)||!pack.criteria.length)throw new TypeError('pack requires id, title and criteria');for(const c of pack.criteria){if(!c.id||!c.instructions||!Number.isFinite(c.weight)||c.weight<=0||!c.criteria||Object.keys(c.criteria).sort().join(',')!=='a,b')throw new TypeError('each criterion requires id, instructions, positive weight and exactly a/b criteria')}return pack}
export async function loadPack(value){const p=value.includes('/')||value.endsWith('.json')?value:join(ROOT,'packs',`${value}.json`);return validatePack(JSON.parse(await readFile(p,'utf8')))}
export function tally(answers,pack){let a=0,b=0;const breakdown=pack.criteria.map(c=>{const winner=answers[c.id].choice;winner==='a'?a+=c.weight:b+=c.weight;return{id:c.id,winner,weight:c.weight,probabilities:answers[c.id].probabilities}});return{winner:a===b?'tie':a>b?'a':'b',scores:{a,b},breakdown}}
export async function duel(a,b,{pack,provider}){if(!String(a).trim()||!String(b).trim())throw new TypeError('both options are required');const questions=Object.fromEntries(pack.criteria.map(c=>[c.id,{type:'choice',instructions:c.instructions,criteria:{a:c.criteria.a,b:c.criteria.b}}]));const r=await provider({state:{a,b},questions});return{a,b,...tally(r.answers,pack),model:r.model,usage:{...r.usage,estimated_cost_usd:estimateCostUsd(r.usage.input_tokens)}}}
export function padBracket(options){if(options.length<3||options.length>64)throw new RangeError('bracket requires 3 to 64 options');const size=2**Math.ceil(Math.log2(options.length)),byes=size-options.length,out=[];for(let i=0;i<byes;i++)out.push(options[i],null);out.push(...options.slice(byes));return out}
async function parallel(items,limit,fn){let i=0;const out=[];await Promise.all(Array.from({length:Math.min(limit,items.length)},async()=>{while(i<items.length){const n=i++;out[n]=await fn(items[n],n)}}));return out}
export async function bracket(options,{pack,provider,concurrency=8,onMatch=()=>{}}){let current=padBracket(options),round=0;const matches=[];while(current.length>1){const pairs=[];for(let i=0;i<current.length;i+=2)pairs.push([current[i],current[i+1]]);const completed=await parallel(pairs,concurrency,async([a,b],slot)=>{let result;if(a===null||b===null){const winner=a??b;result={round,slot,a,b,winner,bye:true}}else{const judged=await duel(a,b,{pack,provider});const winner=judged.winner==='tie'?a:judged[judged.winner];result={round,slot,...judged,winner,bye:false}}matches.push(result);await onMatch(result);return result});current=completed.map(x=>x.winner);round++}return{winner:current[0],rounds:round,matches}}
export function estimateBracket(options,pack){const size=2**Math.ceil(Math.log2(options.length));const calls=options.length-1;const per=estimateTokens({state:{a:options[0]||'A',b:options[1]||'B'},questions:Object.fromEntries(pack.criteria.map(c=>[c.id,{type:'choice',instructions:c.instructions,criteria:c.criteria}]))});return{slots:size,byes:size-options.length,requests:calls,estimatedInputTokens:calls*per,estimatedCostUsd:estimateCostUsd(calls*per)}}
export async function appendHistory(entry,path=join(process.cwd(),'local-data','duels.jsonl')){await mkdir(dirname(path),{recursive:true});await appendFile(path,`${JSON.stringify({...entry,timestamp:entry.timestamp??new Date().toISOString()})}\n`,{mode:0o600});return path}
export async function readHistory(path=join(process.cwd(),'local-data','duels.jsonl')){try{return(await readFile(path,'utf8')).trim().split('\n').filter(Boolean).map(JSON.parse)}catch(e){if(e.code==='ENOENT')return[];throw e}}
function send(res,status,type,body){res.writeHead(status,{'content-type':`${type}; charset=utf-8`});res.end(body)}async function body(req){const a=[];for await(const c of req)a.push(c);return JSON.parse(Buffer.concat(a))}
export function createArenaServer({provider,pack,historyPath}={}){return createServer(async(req,res)=>{try{const u=new URL(req.url,'http://localhost');if(req.method==='GET'&&u.pathname==='/')return send(res,200,'text/html','<!doctype html><title>Jev Duel Arena</title><style>body{font:20px system-ui;max-width:700px;margin:60px auto;background:#101218;color:#fff}input,button{font:inherit;padding:12px;margin:6px}</style><h1>Duel Arena</h1><form id=f><input name=a placeholder="Option A"><input name=b placeholder="Option B"><button>Duel</button></form><pre id=o></pre><script>f.onsubmit=async e=>{e.preventDefault();o.textContent=await(await fetch(`/duel`,{method:`POST`,headers:{`content-type`:`application/json`},body:JSON.stringify(Object.fromEntries(new FormData(f)))})).text()}</script>');if(req.method==='GET'&&u.pathname==='/history')return send(res,200,'application/json',JSON.stringify(await readHistory(historyPath)));if(req.method==='POST'&&u.pathname==='/duel'){const x=await body(req),r=await duel(x.a,x.b,{pack,provider});await appendHistory(r,historyPath);return send(res,200,'application/json',JSON.stringify(r,null,2))}send(res,404,'application/json','{"error":"not_found"}')}catch(e){send(res,400,'application/json',JSON.stringify({error:e.message}))}})}
